# A CloudFormation stack containing all resources except for the S3 bucket containing the statefun application JAR.
Resources:
  ManagedFlinkIngressStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      StreamModeDetails:
        StreamMode: PROVISIONED
  ManagedFlinkEgressStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      StreamModeDetails:
        StreamMode: PROVISIONED
  ManagedFlinkLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: 
        !Sub ${AWS::StackName}-log-group-${AWS::AccountId}
      RetentionInDays: 7
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  ManagedFlinkLogStream:
    Type: 'AWS::Logs::LogStream'
    Properties:
      LogGroupName: 
        Ref: ManagedFlinkLogGroup
      LogStreamName:
        !Sub ${AWS::StackName}-log-stream-${AWS::AccountId}
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  ManagedFlinkIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - kinesisanalytics.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 'kinesis:DescribeStream'
                  - 'kinesis:GetRecords'
                  - 'kinesis:GetShardIterator'
                  - 'kinesis:ListShards'
                Effect: Allow
                Resource:
                  - 'Fn::GetAtt':
                    - ManagedFlinkIngressStream
                    - Arn
                  - 'Fn::GetAtt':
                    - ManagedFlinkEgressStream
                    - Arn                    
            Version: '2012-10-17'
          PolicyName: AccessKDSPolicy
        - PolicyDocument:
            Statement:
              - Action:
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                Effect: Allow
                Resource:
                  'Fn::GetAtt':
                    - ManagedFlinkLogGroup
                    - Arn
            Version: '2012-10-17'
          PolicyName: AccessCWLogsPolicy
        - PolicyDocument:
            Statement:
              - Action: 'cloudwatch:PutMetricData'
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: AccessCWMetricsPolicy          
  ManagedFlinkApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      ApplicationName: 'ExampleManagedFlinkApplication'
      ApplicationDescription: 'Example Managed Flink Application'
      RuntimeEnvironment: 'FLINK-1_18'
      ServiceExecutionRole: !GetAtt ManagedFlinkIAMRole.Arn
      ApplicationConfiguration:
        EnvironmentProperties:
          PropertyGroups:
            - PropertyGroupId: 'StatefunApplicationProperties'
              PropertyMap:
                EVENTS_INGRESS_STREAM_DEFAULT: !Ref ManagedFlinkIngressStream
                EVENTS_EGRESS_STREAM_DEFAULT: !Ref ManagedFlinkEgressStream
                AWS_REGION: !Ref AWS::Region
        FlinkApplicationConfiguration:
          CheckpointConfiguration:
            ConfigurationType: 'CUSTOM'
            CheckpointingEnabled: True
            CheckpointInterval: 900000 # Every fifteen minutes
            MinPauseBetweenCheckpoints: 500
          MonitoringConfiguration:
            ConfigurationType: 'CUSTOM'
            MetricsLevel: 'APPLICATION'
            LogLevel: 'INFO'
          ParallelismConfiguration:
            ConfigurationType: 'CUSTOM'
            Parallelism: 1
            ParallelismPerKPU: 1
            AutoScalingEnabled: True
        ApplicationSnapshotConfiguration:
          SnapshotsEnabled: True
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: !ImportValue ManagedFlinkCodeBucketArn # Created and exported by the stack defined in managed-flink-poc-bucket.yaml
              FileKey: "my-stateful-functions-embedded-java-3.3.0.jar"
          CodeContentType: 'ZIPFILE' 

