apiVersion: example.com/v1alpha1
kind: ManagedFlink
metadata:
  name: flink-demo
  namespace: default
spec:
  resourceConfig:
    codeBucket: flink-demo-bucket
    codeFile: my-stateful-functions-embedded-java-3.3.0.jar
    # The composition will generate a role with basic permissions for the application (e.g. logging, metrics), but
    # it doesn't know what additional permissions the application needs. You can specify them here...
    additionalPermissions:
      managedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
      inlinePolicies:
        - name: kinesis_policy
          policy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Resource": [
                    "arn:aws:kinesis:us-east-2:000000000000:stream/flink-demo-ingress",
                    "arn:aws:kinesis:us-east-2:000000000000:stream/flink-demo-egress"
                  ],
                  "Action": [
                    "kinesis:DescribeStream",
                    "kinesis:GetRecords",
                    "kinesis:GetShardIterator",
                    "kinesis:ListShards",
                    "kinesis:PutRecord"
                  ]
                }
              ]
            }
    environmentProperties:
      - propertyGroup:
          - propertyGroupId: StatefunApplicationProperties
            propertyMap:
              EVENTS_INGRESS_STREAM_DEFAULT: flink-demo-ingress
              EVENTS_EGRESS_STREAM_DEFAULT: flink-demo-egress
