apiVersion: kellinwood.com/v1alpha1
kind: ManagedFlink
metadata:
  name: flink-demo2
  namespace: default
spec:
  resourceConfig:
    region: us-east-2
    name: flink-demo2
    codeBucket: flink-demo-bucket
    codeFile: my-stateful-functions-embedded-java-3.3.0.jar
    runtime: FLINK-1_18
    parallelism: 1
    environmentProperties:
      - propertyGroup:
          - propertyGroupId: StatefunApplicationProperties
            propertyMap:
              EVENTS_INGRESS_STREAM_DEFAULT: arn:aws:kinesis:us-east-2:000000000000:stream/flink-demo-ingress
              EVENTS_EGRESS_STREAM_DEFAULT: arn:aws:kinesis:us-east-2:000000000000:stream/flink-demo-egress
              AWS_REGION: us-east-2
              FOO: bar
  compositionSelector:
    matchLabels:
      appReadyHandler: lambda


