---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: managedflink.example.com
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: XManagedFlink
  mode: Pipeline
  pipeline:
  - step: environment-configs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
          - type: Reference
            ref:
              name: aws-env-config
  - step: render
    functionRef:
      name: function-managed-flink
  - step: auto-ready-composite-resource # Auto-sets ready on the XR when the composed resources are ready
    functionRef:
      name: function-auto-ready
