apiVersion: kellinwood.com/v1alpha1
kind: ManagedFlink
metadata:
  name: flink-demo
  namespace: default
spec:
  resourceConfig:
    region: us-east-2
    name: flink-demo
    codeBucket: flink-demo-bucket
    codeFile: my-stateful-functions-embedded-java-3.3.0.jar
    runtime: FLINK-1_18
    parallelism: 1
    environmentProperties:
      - propertyGroup:
          - propertyGroupId: StatefunApplicationProperties
            propertyMap:
              EVENTS_INGRESS_STREAM_DEFAULT: flink-demo-ingress
              EVENTS_EGRESS_STREAM_DEFAULT: flink-demo-egress
              AWS_REGION: us-east-2
  compositionSelector:
    matchLabels:
      appReadyHandler: none # Use the composition that doesn't provision a lambda function to handle the app ready signal


